CREATE TABLE farm_runs (
 record_id TEXT PRIMARY KEY NOT NULL,
 record_schema_version INTEGER NOT NULL CHECK(record_schema_version IS NULL OR typeof(record_schema_version)='integer'),
 preset_id TEXT NOT NULL,
 preset_version INTEGER NOT NULL CHECK(preset_version IS NULL OR typeof(preset_version)='integer'),
 status TEXT NOT NULL,
 character TEXT NOT NULL,
 realm TEXT NOT NULL,
 session_id TEXT,
 started_at INTEGER CHECK(started_at IS NULL OR typeof(started_at)='integer'),
 finished_at INTEGER CHECK(finished_at IS NULL OR typeof(finished_at)='integer'),
 completed_at INTEGER CHECK(completed_at IS NULL OR typeof(completed_at)='integer'),
 duration_seconds INTEGER CHECK(duration_seconds IS NULL OR typeof(duration_seconds)='integer'),
 start_zone TEXT,
 end_zone TEXT,
 start_instance_name TEXT,
 end_instance_name TEXT,
 instance_id INTEGER CHECK(instance_id IS NULL OR typeof(instance_id)='integer'),
 difficulty_id INTEGER CHECK(difficulty_id IS NULL OR typeof(difficulty_id)='integer'),
 run_number_local_day INTEGER CHECK(run_number_local_day IS NULL OR typeof(run_number_local_day)='integer'),
 local_day TEXT,
 day_offset_minutes INTEGER CHECK(day_offset_minutes IS NULL OR typeof(day_offset_minutes)='integer'),
 start_gold_copper INTEGER CHECK(start_gold_copper IS NULL OR typeof(start_gold_copper)='integer'),
 end_gold_copper INTEGER CHECK(end_gold_copper IS NULL OR typeof(end_gold_copper)='integer'),
 raw_gold_delta_copper INTEGER CHECK(raw_gold_delta_copper IS NULL OR typeof(raw_gold_delta_copper)='integer'),
 started_manually INTEGER NOT NULL CHECK(started_manually IN (0,1)),
 finished_manually INTEGER NOT NULL CHECK(finished_manually IN (0,1)),
 reset_confirmed INTEGER NOT NULL CHECK(reset_confirmed IN (0,1)),
 interruption_reason TEXT,
 note TEXT,
 created_at INTEGER NOT NULL CHECK(created_at IS NULL OR typeof(created_at)='integer'),
 updated_at INTEGER NOT NULL CHECK(updated_at IS NULL OR typeof(updated_at)='integer'),
 addon_schema_version INTEGER NOT NULL CHECK(addon_schema_version IS NULL OR typeof(addon_schema_version)='integer'),
 revision INTEGER NOT NULL CHECK(revision IS NULL OR typeof(revision)='integer'),
 character_id INTEGER NOT NULL REFERENCES source_identities(id),
 source_file_sha256 TEXT NOT NULL,
 source_schema_version TEXT NOT NULL,
 source_record_index INTEGER NOT NULL,
 source_dataset TEXT NOT NULL,
 import_batch_id TEXT NOT NULL REFERENCES import_batches(id),
 logical_payload TEXT NOT NULL,
 raw_record TEXT NOT NULL,
 CHECK(record_schema_version=1 AND addon_schema_version=5 AND preset_version>0),
 CHECK(status IN ('prepared','running','review','completed','abandoned','incomplete')),
 CHECK(created_at>=0 AND updated_at>=created_at AND revision>=0),
 CHECK(started_at IS NULL OR started_at>=created_at),
 CHECK(finished_at IS NULL OR (started_at IS NOT NULL AND finished_at>=started_at AND duration_seconds IS NOT NULL AND duration_seconds=finished_at-started_at)),
 CHECK(duration_seconds IS NULL OR duration_seconds>=0),
 CHECK(start_gold_copper IS NULL OR start_gold_copper>=0),
 CHECK(end_gold_copper IS NULL OR end_gold_copper>=0),
 CHECK((start_gold_copper IS NULL OR end_gold_copper IS NULL) AND raw_gold_delta_copper IS NULL OR (start_gold_copper IS NOT NULL AND end_gold_copper IS NOT NULL AND raw_gold_delta_copper IS NOT NULL AND raw_gold_delta_copper=end_gold_copper-start_gold_copper)),
 CHECK(status!='completed' OR (completed_at IS NOT NULL AND finished_at IS NOT NULL AND completed_at>=finished_at AND reset_confirmed=1)),
 CHECK(status='prepared' AND revision=0 AND started_at IS NULL)
);
CREATE TABLE farm_run_events (
 record_id TEXT PRIMARY KEY NOT NULL,
 record_schema_version INTEGER NOT NULL CHECK(record_schema_version IS NULL OR typeof(record_schema_version)='integer'),
 preset_id TEXT NOT NULL,
 preset_version INTEGER NOT NULL CHECK(preset_version IS NULL OR typeof(preset_version)='integer'),
 status TEXT NOT NULL,
 character TEXT NOT NULL,
 realm TEXT NOT NULL,
 session_id TEXT,
 started_at INTEGER CHECK(started_at IS NULL OR typeof(started_at)='integer'),
 finished_at INTEGER CHECK(finished_at IS NULL OR typeof(finished_at)='integer'),
 completed_at INTEGER CHECK(completed_at IS NULL OR typeof(completed_at)='integer'),
 duration_seconds INTEGER CHECK(duration_seconds IS NULL OR typeof(duration_seconds)='integer'),
 start_zone TEXT,
 end_zone TEXT,
 start_instance_name TEXT,
 end_instance_name TEXT,
 instance_id INTEGER CHECK(instance_id IS NULL OR typeof(instance_id)='integer'),
 difficulty_id INTEGER CHECK(difficulty_id IS NULL OR typeof(difficulty_id)='integer'),
 run_number_local_day INTEGER CHECK(run_number_local_day IS NULL OR typeof(run_number_local_day)='integer'),
 local_day TEXT,
 day_offset_minutes INTEGER CHECK(day_offset_minutes IS NULL OR typeof(day_offset_minutes)='integer'),
 start_gold_copper INTEGER CHECK(start_gold_copper IS NULL OR typeof(start_gold_copper)='integer'),
 end_gold_copper INTEGER CHECK(end_gold_copper IS NULL OR typeof(end_gold_copper)='integer'),
 raw_gold_delta_copper INTEGER CHECK(raw_gold_delta_copper IS NULL OR typeof(raw_gold_delta_copper)='integer'),
 started_manually INTEGER NOT NULL CHECK(started_manually IN (0,1)),
 finished_manually INTEGER NOT NULL CHECK(finished_manually IN (0,1)),
 reset_confirmed INTEGER NOT NULL CHECK(reset_confirmed IN (0,1)),
 interruption_reason TEXT,
 note TEXT,
 created_at INTEGER NOT NULL CHECK(created_at IS NULL OR typeof(created_at)='integer'),
 updated_at INTEGER NOT NULL CHECK(updated_at IS NULL OR typeof(updated_at)='integer'),
 addon_schema_version INTEGER NOT NULL CHECK(addon_schema_version IS NULL OR typeof(addon_schema_version)='integer'),
 revision INTEGER NOT NULL CHECK(revision IS NULL OR typeof(revision)='integer'),
 farm_run_id TEXT NOT NULL REFERENCES farm_runs(record_id),
 event_type TEXT NOT NULL,
 from_status TEXT NOT NULL,
 time INTEGER NOT NULL CHECK(time IS NULL OR typeof(time)='integer'),
 character_id INTEGER NOT NULL REFERENCES source_identities(id),
 source_file_sha256 TEXT NOT NULL,
 source_schema_version TEXT NOT NULL,
 source_record_index INTEGER NOT NULL,
 source_dataset TEXT NOT NULL,
 import_batch_id TEXT NOT NULL REFERENCES import_batches(id),
 logical_payload TEXT NOT NULL,
 raw_record TEXT NOT NULL,
 CHECK(record_schema_version=1 AND addon_schema_version=5 AND preset_version>0),
 CHECK(status IN ('prepared','running','review','completed','abandoned','incomplete')),
 CHECK(created_at>=0 AND updated_at>=created_at AND revision>=0),
 CHECK(started_at IS NULL OR started_at>=created_at),
 CHECK(finished_at IS NULL OR (started_at IS NOT NULL AND finished_at>=started_at AND duration_seconds IS NOT NULL AND duration_seconds=finished_at-started_at)),
 CHECK(duration_seconds IS NULL OR duration_seconds>=0),
 CHECK(start_gold_copper IS NULL OR start_gold_copper>=0),
 CHECK(end_gold_copper IS NULL OR end_gold_copper>=0),
 CHECK((start_gold_copper IS NULL OR end_gold_copper IS NULL) AND raw_gold_delta_copper IS NULL OR (start_gold_copper IS NOT NULL AND end_gold_copper IS NOT NULL AND raw_gold_delta_copper IS NOT NULL AND raw_gold_delta_copper=end_gold_copper-start_gold_copper)),
 CHECK(status!='completed' OR (completed_at IS NOT NULL AND finished_at IS NOT NULL AND completed_at>=finished_at AND reset_confirmed=1)),
 UNIQUE(farm_run_id,revision),
 CHECK(event_type IN ('prepared','started','finish_requested','completed','abandoned','interrupted','note_added')),
 CHECK(time=updated_at AND revision>0)
);
CREATE INDEX idx_farm_identity_start ON farm_run_events(character_id,started_at);
CREATE INDEX idx_farm_preset ON farm_runs(preset_id);
CREATE INDEX idx_farm_status ON farm_run_events(status);
CREATE INDEX idx_farm_session ON farm_run_events(session_id);
CREATE INDEX idx_farm_day ON farm_run_events(character_id,local_day);
CREATE INDEX idx_farm_event_time ON farm_run_events(time);
